= Brief ðŸ“‚
:Date: 12/15/2019
:Revision: 2.0.0-alpha
:Author: Ben Martinez-Bateman
:Email: ben@alwaysblank.org
:toc: macro
:toclevels: 6
:toc-title:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
ifndef::env-github[]
:tip-caption: ðŸ’¡
:note-caption: â„¹
:important-caption: â—
:caution-caption: ðŸ”¥
:warning-caption: âš 
endif::[]

**Present your arguments.**

image:https://travis-ci.org/alwaysblank/brief.svg?branch=master["Build Status", link="https://travis-ci.org/alwaysblank/brief"]

toc::[]

== What Is This?

It's a simple little tool for passing around collections of variable stuctured data.

90% of the reason I built it was because I got very tired of writing `isset()`, etc, conditionals when _the nonexistence of a key was equivalent to a falsey value in terms of program flow_.
It grew from there to provide some other functionality related to moving collections of structure data around.
I find it particularly useful when templating with https://laravel.com/docs/5.8/blade[Laravel Blade].

(Brief is only one way to solve the issues I might use here as examples:
It's not intended to be an authoritative or "best" solution, merely a convenient one, if you find it convenient.)

== How Does It Work?

[source,php]
----
$Brief = Brief::make([
    'key' => 'value',
]);

$Brief->key;
// 'value'

$Brief->doesnt_exist;
// null
----

Instead of throwing an error or exception, Brief will return `null` if a key does not have an associated value.

[NOTE]
====
You can also create a Brief with `new`, `make()` is just slightly more concise:
[source,php]
----
$Brief = new Brief([
    'key' => 'value',
]);
----
====

=== Logging

Since the basic concept for Brief is about how either your data exists or doesn't, Brief will not complain loudly if you do something it doesn't like.
If it's recoverable, it will simply recover and move on, with your data likely lost.
In most cases, this should be fine; Your logic will have something to do if Brief gives you `null` for a piece of data you thought you'd added.

In some situations, though, you don't want this--you want to know what's happened.
Fortunately, Brief includes a very simple logging feature.
To use it, just do the following:

[source,php]
----
$brief = new Brief(
    ['key' => 'value'],
    ['logger' => function($name, $description, $clone, $data) {
        // Do something with this data
    }]
);
----

In this example, whenever Brief encounters errors that it has some understanding of, an error message will be passed to the callable you've defined here.
If instead of a callable you pass boolean `true` to the `logger` setting, then it will just dispatch an canned message to PHP's `error_log()` and your system will handle that however it's configured to.

[WARNING]
====
This method is only fired on problems Brief is equipped to understand and expect;
it will not, for instance, catch an exception you throw during `transform()`.
====

[NOTE]
====
If you used v1 of Brief, then these logger calls happen in the same places where Brief used to throw Exceptions, and replace that functionality;
Brief will not longer throw Exceptions of its own volition.
====